fragment BloggParts on Blogg {
  __typename
  title
  excerpt
  date
  category
  readingTime
  coverImage
  body
}

fragment ArrangementerParts on Arrangementer {
  __typename
  title
  description
  date
  endDate
  time
  location
  price
  capacity
  category
  isOnline
  registrationUrl
  body
}

fragment PagesParts on Pages {
  __typename
  title
  subtitle
  intro
  body
}

fragment TjenesterParts on Tjenester {
  __typename
  tittel
  undertittel
  badge
  beskrivelse
  detaljer
  priser {
    __typename
    label
    pris
  }
  orden
}

fragment UtdanningParts on Utdanning {
  __typename
  ar
  grad
  sted
}
