//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  blogg: Blogg;
  bloggConnection: BloggConnection;
  arrangementer: Arrangementer;
  arrangementerConnection: ArrangementerConnection;
  sider: Sider;
  siderConnection: SiderConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBloggArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBloggConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BloggFilter>;
};


export type QueryArrangementerArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryArrangementerConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ArrangementerFilter>;
};


export type QuerySiderArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiderConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiderFilter>;
};

export type DocumentFilter = {
  blogg?: InputMaybe<BloggFilter>;
  arrangementer?: InputMaybe<ArrangementerFilter>;
  sider?: InputMaybe<SiderFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Blogg | Arrangementer | Sider | Folder;

export type Blogg = Node & Document & {
  __typename?: 'Blogg';
  title: Scalars['String']['output'];
  excerpt: Scalars['String']['output'];
  date: Scalars['String']['output'];
  category?: Maybe<Scalars['String']['output']>;
  readingTime?: Maybe<Scalars['Float']['output']>;
  coverImage?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type BloggFilter = {
  title?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  category?: InputMaybe<StringFilter>;
  readingTime?: InputMaybe<NumberFilter>;
  coverImage?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type BloggConnectionEdges = {
  __typename?: 'BloggConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Blogg>;
};

export type BloggConnection = Connection & {
  __typename?: 'BloggConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BloggConnectionEdges>>>;
};

export type Arrangementer = Node & Document & {
  __typename?: 'Arrangementer';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  date: Scalars['String']['output'];
  endDate?: Maybe<Scalars['String']['output']>;
  time: Scalars['String']['output'];
  location: Scalars['String']['output'];
  price: Scalars['Float']['output'];
  capacity?: Maybe<Scalars['Float']['output']>;
  category: Scalars['String']['output'];
  isOnline?: Maybe<Scalars['Boolean']['output']>;
  registrationUrl?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ArrangementerFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  endDate?: InputMaybe<DatetimeFilter>;
  time?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  price?: InputMaybe<NumberFilter>;
  capacity?: InputMaybe<NumberFilter>;
  category?: InputMaybe<StringFilter>;
  isOnline?: InputMaybe<BooleanFilter>;
  registrationUrl?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ArrangementerConnectionEdges = {
  __typename?: 'ArrangementerConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Arrangementer>;
};

export type ArrangementerConnection = Connection & {
  __typename?: 'ArrangementerConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ArrangementerConnectionEdges>>>;
};

export type Sider = Node & Document & {
  __typename?: 'Sider';
  title: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SiderFilter = {
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type SiderConnectionEdges = {
  __typename?: 'SiderConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Sider>;
};

export type SiderConnection = Connection & {
  __typename?: 'SiderConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiderConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateBlogg: Blogg;
  createBlogg: Blogg;
  updateArrangementer: Arrangementer;
  createArrangementer: Arrangementer;
  updateSider: Sider;
  createSider: Sider;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateBloggArgs = {
  relativePath: Scalars['String']['input'];
  params: BloggMutation;
};


export type MutationCreateBloggArgs = {
  relativePath: Scalars['String']['input'];
  params: BloggMutation;
};


export type MutationUpdateArrangementerArgs = {
  relativePath: Scalars['String']['input'];
  params: ArrangementerMutation;
};


export type MutationCreateArrangementerArgs = {
  relativePath: Scalars['String']['input'];
  params: ArrangementerMutation;
};


export type MutationUpdateSiderArgs = {
  relativePath: Scalars['String']['input'];
  params: SiderMutation;
};


export type MutationCreateSiderArgs = {
  relativePath: Scalars['String']['input'];
  params: SiderMutation;
};

export type DocumentUpdateMutation = {
  blogg?: InputMaybe<BloggMutation>;
  arrangementer?: InputMaybe<ArrangementerMutation>;
  sider?: InputMaybe<SiderMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  blogg?: InputMaybe<BloggMutation>;
  arrangementer?: InputMaybe<ArrangementerMutation>;
  sider?: InputMaybe<SiderMutation>;
};

export type BloggMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  readingTime?: InputMaybe<Scalars['Float']['input']>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ArrangementerMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  endDate?: InputMaybe<Scalars['String']['input']>;
  time?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['Float']['input']>;
  capacity?: InputMaybe<Scalars['Float']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  isOnline?: InputMaybe<Scalars['Boolean']['input']>;
  registrationUrl?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type SiderMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type BloggPartsFragment = { __typename: 'Blogg', title: string, excerpt: string, date: string, category?: string | null, readingTime?: number | null, coverImage?: string | null, body?: any | null };

export type ArrangementerPartsFragment = { __typename: 'Arrangementer', title: string, description: string, date: string, endDate?: string | null, time: string, location: string, price: number, capacity?: number | null, category: string, isOnline?: boolean | null, registrationUrl?: string | null, body?: any | null };

export type SiderPartsFragment = { __typename: 'Sider', title: string, body?: any | null };

export type BloggQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BloggQuery = { __typename?: 'Query', blogg: { __typename: 'Blogg', id: string, title: string, excerpt: string, date: string, category?: string | null, readingTime?: number | null, coverImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type BloggConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BloggFilter>;
}>;


export type BloggConnectionQuery = { __typename?: 'Query', bloggConnection: { __typename?: 'BloggConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BloggConnectionEdges', cursor: string, node?: { __typename: 'Blogg', id: string, title: string, excerpt: string, date: string, category?: string | null, readingTime?: number | null, coverImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ArrangementerQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ArrangementerQuery = { __typename?: 'Query', arrangementer: { __typename: 'Arrangementer', id: string, title: string, description: string, date: string, endDate?: string | null, time: string, location: string, price: number, capacity?: number | null, category: string, isOnline?: boolean | null, registrationUrl?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ArrangementerConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ArrangementerFilter>;
}>;


export type ArrangementerConnectionQuery = { __typename?: 'Query', arrangementerConnection: { __typename?: 'ArrangementerConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ArrangementerConnectionEdges', cursor: string, node?: { __typename: 'Arrangementer', id: string, title: string, description: string, date: string, endDate?: string | null, time: string, location: string, price: number, capacity?: number | null, category: string, isOnline?: boolean | null, registrationUrl?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SiderQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SiderQuery = { __typename?: 'Query', sider: { __typename: 'Sider', id: string, title: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SiderConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiderFilter>;
}>;


export type SiderConnectionQuery = { __typename?: 'Query', siderConnection: { __typename?: 'SiderConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SiderConnectionEdges', cursor: string, node?: { __typename: 'Sider', id: string, title: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const BloggPartsFragmentDoc = gql`
    fragment BloggParts on Blogg {
  __typename
  title
  excerpt
  date
  category
  readingTime
  coverImage
  body
}
    `;
export const ArrangementerPartsFragmentDoc = gql`
    fragment ArrangementerParts on Arrangementer {
  __typename
  title
  description
  date
  endDate
  time
  location
  price
  capacity
  category
  isOnline
  registrationUrl
  body
}
    `;
export const SiderPartsFragmentDoc = gql`
    fragment SiderParts on Sider {
  __typename
  title
  body
}
    `;
export const BloggDocument = gql`
    query blogg($relativePath: String!) {
  blogg(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BloggParts
  }
}
    ${BloggPartsFragmentDoc}`;
export const BloggConnectionDocument = gql`
    query bloggConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BloggFilter) {
  bloggConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BloggParts
      }
    }
  }
}
    ${BloggPartsFragmentDoc}`;
export const ArrangementerDocument = gql`
    query arrangementer($relativePath: String!) {
  arrangementer(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ArrangementerParts
  }
}
    ${ArrangementerPartsFragmentDoc}`;
export const ArrangementerConnectionDocument = gql`
    query arrangementerConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ArrangementerFilter) {
  arrangementerConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ArrangementerParts
      }
    }
  }
}
    ${ArrangementerPartsFragmentDoc}`;
export const SiderDocument = gql`
    query sider($relativePath: String!) {
  sider(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiderParts
  }
}
    ${SiderPartsFragmentDoc}`;
export const SiderConnectionDocument = gql`
    query siderConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiderFilter) {
  siderConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiderParts
      }
    }
  }
}
    ${SiderPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      blogg(variables: BloggQueryVariables, options?: C): Promise<{data: BloggQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BloggQueryVariables, query: string}> {
        return requester<{data: BloggQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BloggQueryVariables, query: string}, BloggQueryVariables>(BloggDocument, variables, options);
      },
    bloggConnection(variables?: BloggConnectionQueryVariables, options?: C): Promise<{data: BloggConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BloggConnectionQueryVariables, query: string}> {
        return requester<{data: BloggConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BloggConnectionQueryVariables, query: string}, BloggConnectionQueryVariables>(BloggConnectionDocument, variables, options);
      },
    arrangementer(variables: ArrangementerQueryVariables, options?: C): Promise<{data: ArrangementerQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArrangementerQueryVariables, query: string}> {
        return requester<{data: ArrangementerQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArrangementerQueryVariables, query: string}, ArrangementerQueryVariables>(ArrangementerDocument, variables, options);
      },
    arrangementerConnection(variables?: ArrangementerConnectionQueryVariables, options?: C): Promise<{data: ArrangementerConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArrangementerConnectionQueryVariables, query: string}> {
        return requester<{data: ArrangementerConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArrangementerConnectionQueryVariables, query: string}, ArrangementerConnectionQueryVariables>(ArrangementerConnectionDocument, variables, options);
      },
    sider(variables: SiderQueryVariables, options?: C): Promise<{data: SiderQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiderQueryVariables, query: string}> {
        return requester<{data: SiderQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiderQueryVariables, query: string}, SiderQueryVariables>(SiderDocument, variables, options);
      },
    siderConnection(variables?: SiderConnectionQueryVariables, options?: C): Promise<{data: SiderConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiderConnectionQueryVariables, query: string}> {
        return requester<{data: SiderConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiderConnectionQueryVariables, query: string}, SiderConnectionQueryVariables>(SiderConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  