//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  /** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  pages: Pages;
  pagesConnection: PagesConnection;
  utdanning: Utdanning;
  utdanningConnection: UtdanningConnection;
  tjenester: Tjenester;
  tjenesterConnection: TjenesterConnection;
  blogg: Blogg;
  bloggConnection: BloggConnection;
  arrangementer: Arrangementer;
  arrangementerConnection: ArrangementerConnection;
  kategorier: Kategorier;
  kategorierConnection: KategorierConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPagesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPagesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PagesFilter>;
};


export type QueryUtdanningArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryUtdanningConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<UtdanningFilter>;
};


export type QueryTjenesterArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTjenesterConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TjenesterFilter>;
};


export type QueryBloggArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBloggConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BloggFilter>;
};


export type QueryArrangementerArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryArrangementerConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ArrangementerFilter>;
};


export type QueryKategorierArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryKategorierConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<KategorierFilter>;
};

export type DocumentFilter = {
  pages?: InputMaybe<PagesFilter>;
  utdanning?: InputMaybe<UtdanningFilter>;
  tjenester?: InputMaybe<TjenesterFilter>;
  blogg?: InputMaybe<BloggFilter>;
  arrangementer?: InputMaybe<ArrangementerFilter>;
  kategorier?: InputMaybe<KategorierFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = PagesHomepage | PagesStandard | PagesHeader | PagesServices | PagesKontakt | Utdanning | Tjenester | Blogg | Arrangementer | Kategorier | Folder;

export type PagesHomepageTestimonials = {
  __typename?: 'PagesHomepageTestimonials';
  quote: Scalars['String']['output'];
  name: Scalars['String']['output'];
  role?: Maybe<Scalars['String']['output']>;
};

export type PagesHomepage = Node & Document & {
  __typename?: 'PagesHomepage';
  heroImage?: Maybe<Scalars['String']['output']>;
  kicker?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
  stat1Value?: Maybe<Scalars['String']['output']>;
  stat1Label?: Maybe<Scalars['String']['output']>;
  stat2Value?: Maybe<Scalars['String']['output']>;
  stat2Label?: Maybe<Scalars['String']['output']>;
  stat3Value?: Maybe<Scalars['String']['output']>;
  stat3Label?: Maybe<Scalars['String']['output']>;
  servicesHeading?: Maybe<Scalars['String']['output']>;
  aboutName?: Maybe<Scalars['String']['output']>;
  aboutText1?: Maybe<Scalars['String']['output']>;
  aboutText2?: Maybe<Scalars['String']['output']>;
  profileImage?: Maybe<Scalars['String']['output']>;
  testimonials?: Maybe<Array<Maybe<PagesHomepageTestimonials>>>;
  blogHeading?: Maybe<Scalars['String']['output']>;
  ctaTitle?: Maybe<Scalars['String']['output']>;
  ctaDescription?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PagesStandardVerdier = {
  __typename?: 'PagesStandardVerdier';
  tittel: Scalars['String']['output'];
  tekst: Scalars['String']['output'];
};

export type PagesStandard = Node & Document & {
  __typename?: 'PagesStandard';
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  profileImage?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  verdier?: Maybe<Array<Maybe<PagesStandardVerdier>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PagesHeader = Node & Document & {
  __typename?: 'PagesHeader';
  title: Scalars['String']['output'];
  intro?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PagesServicesFaq = {
  __typename?: 'PagesServicesFaq';
  question: Scalars['String']['output'];
  answer: Scalars['String']['output'];
};

export type PagesServices = Node & Document & {
  __typename?: 'PagesServices';
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  infoBadge?: Maybe<Scalars['String']['output']>;
  faq?: Maybe<Array<Maybe<PagesServicesFaq>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PagesKontakt = Node & Document & {
  __typename?: 'PagesKontakt';
  title: Scalars['String']['output'];
  kicker?: Maybe<Scalars['String']['output']>;
  heading: Scalars['String']['output'];
  description: Scalars['String']['output'];
  addressLine1?: Maybe<Scalars['String']['output']>;
  addressLine2?: Maybe<Scalars['String']['output']>;
  addressLine3?: Maybe<Scalars['String']['output']>;
  email: Scalars['String']['output'];
  phone: Scalars['String']['output'];
  facebook?: Maybe<Scalars['String']['output']>;
  instagram?: Maybe<Scalars['String']['output']>;
  whatsapp?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Pages = PagesHomepage | PagesStandard | PagesHeader | PagesServices | PagesKontakt;

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PagesHomepageTestimonialsFilter = {
  quote?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
};

export type PagesHomepageFilter = {
  heroImage?: InputMaybe<ImageFilter>;
  kicker?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  stat1Value?: InputMaybe<StringFilter>;
  stat1Label?: InputMaybe<StringFilter>;
  stat2Value?: InputMaybe<StringFilter>;
  stat2Label?: InputMaybe<StringFilter>;
  stat3Value?: InputMaybe<StringFilter>;
  stat3Label?: InputMaybe<StringFilter>;
  servicesHeading?: InputMaybe<StringFilter>;
  aboutName?: InputMaybe<StringFilter>;
  aboutText1?: InputMaybe<StringFilter>;
  aboutText2?: InputMaybe<StringFilter>;
  profileImage?: InputMaybe<ImageFilter>;
  testimonials?: InputMaybe<PagesHomepageTestimonialsFilter>;
  blogHeading?: InputMaybe<StringFilter>;
  ctaTitle?: InputMaybe<StringFilter>;
  ctaDescription?: InputMaybe<StringFilter>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PagesStandardVerdierFilter = {
  tittel?: InputMaybe<StringFilter>;
  tekst?: InputMaybe<StringFilter>;
};

export type PagesStandardFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  profileImage?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
  verdier?: InputMaybe<PagesStandardVerdierFilter>;
};

export type PagesHeaderFilter = {
  title?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
};

export type PagesServicesFaqFilter = {
  question?: InputMaybe<StringFilter>;
  answer?: InputMaybe<StringFilter>;
};

export type PagesServicesFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  infoBadge?: InputMaybe<StringFilter>;
  faq?: InputMaybe<PagesServicesFaqFilter>;
};

export type PagesKontaktFilter = {
  title?: InputMaybe<StringFilter>;
  kicker?: InputMaybe<StringFilter>;
  heading?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  addressLine1?: InputMaybe<StringFilter>;
  addressLine2?: InputMaybe<StringFilter>;
  addressLine3?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  facebook?: InputMaybe<StringFilter>;
  instagram?: InputMaybe<StringFilter>;
  whatsapp?: InputMaybe<StringFilter>;
};

export type PagesFilter = {
  homepage?: InputMaybe<PagesHomepageFilter>;
  standard?: InputMaybe<PagesStandardFilter>;
  header?: InputMaybe<PagesHeaderFilter>;
  services?: InputMaybe<PagesServicesFilter>;
  kontakt?: InputMaybe<PagesKontaktFilter>;
};

export type PagesConnectionEdges = {
  __typename?: 'PagesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Pages>;
};

export type PagesConnection = Connection & {
  __typename?: 'PagesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PagesConnectionEdges>>>;
};

export type Utdanning = Node & Document & {
  __typename?: 'Utdanning';
  ar: Scalars['String']['output'];
  grad: Scalars['String']['output'];
  sted: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type UtdanningFilter = {
  ar?: InputMaybe<StringFilter>;
  grad?: InputMaybe<StringFilter>;
  sted?: InputMaybe<StringFilter>;
};

export type UtdanningConnectionEdges = {
  __typename?: 'UtdanningConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Utdanning>;
};

export type UtdanningConnection = Connection & {
  __typename?: 'UtdanningConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<UtdanningConnectionEdges>>>;
};

export type TjenesterPriser = {
  __typename?: 'TjenesterPriser';
  label: Scalars['String']['output'];
  pris: Scalars['String']['output'];
};

export type Tjenester = Node & Document & {
  __typename?: 'Tjenester';
  malgruppe: Scalars['String']['output'];
  orden?: Maybe<Scalars['Float']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  tittel: Scalars['String']['output'];
  badge?: Maybe<Scalars['String']['output']>;
  undertittel: Scalars['String']['output'];
  description: Scalars['JSON']['output'];
  detaljer?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  priser?: Maybe<Array<Maybe<TjenesterPriser>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type TjenesterPriserFilter = {
  label?: InputMaybe<StringFilter>;
  pris?: InputMaybe<StringFilter>;
};

export type TjenesterFilter = {
  malgruppe?: InputMaybe<StringFilter>;
  orden?: InputMaybe<NumberFilter>;
  image?: InputMaybe<ImageFilter>;
  tittel?: InputMaybe<StringFilter>;
  badge?: InputMaybe<StringFilter>;
  undertittel?: InputMaybe<StringFilter>;
  description?: InputMaybe<RichTextFilter>;
  detaljer?: InputMaybe<StringFilter>;
  priser?: InputMaybe<TjenesterPriserFilter>;
};

export type TjenesterConnectionEdges = {
  __typename?: 'TjenesterConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Tjenester>;
};

export type TjenesterConnection = Connection & {
  __typename?: 'TjenesterConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TjenesterConnectionEdges>>>;
};

export type Blogg = Node & Document & {
  __typename?: 'Blogg';
  title: Scalars['String']['output'];
  excerpt: Scalars['String']['output'];
  date: Scalars['String']['output'];
  category?: Maybe<Scalars['String']['output']>;
  readingTime?: Maybe<Scalars['Float']['output']>;
  coverImage?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BloggFilter = {
  title?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  category?: InputMaybe<StringFilter>;
  readingTime?: InputMaybe<NumberFilter>;
  coverImage?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type BloggConnectionEdges = {
  __typename?: 'BloggConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Blogg>;
};

export type BloggConnection = Connection & {
  __typename?: 'BloggConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BloggConnectionEdges>>>;
};

export type ArrangementerKategorier = Kategorier;

export type Arrangementer = Node & Document & {
  __typename?: 'Arrangementer';
  title: Scalars['String']['output'];
  description: Scalars['JSON']['output'];
  image?: Maybe<Scalars['String']['output']>;
  date: Scalars['String']['output'];
  endDate?: Maybe<Scalars['String']['output']>;
  time: Scalars['String']['output'];
  location: Scalars['String']['output'];
  price: Scalars['Float']['output'];
  capacity?: Maybe<Scalars['Float']['output']>;
  kategorier: ArrangementerKategorier;
  isOnline?: Maybe<Scalars['Boolean']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ArrangementerKategorierFilter = {
  kategorier?: InputMaybe<KategorierFilter>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ArrangementerFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<RichTextFilter>;
  image?: InputMaybe<ImageFilter>;
  date?: InputMaybe<DatetimeFilter>;
  endDate?: InputMaybe<DatetimeFilter>;
  time?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  price?: InputMaybe<NumberFilter>;
  capacity?: InputMaybe<NumberFilter>;
  kategorier?: InputMaybe<ArrangementerKategorierFilter>;
  isOnline?: InputMaybe<BooleanFilter>;
};

export type ArrangementerConnectionEdges = {
  __typename?: 'ArrangementerConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Arrangementer>;
};

export type ArrangementerConnection = Connection & {
  __typename?: 'ArrangementerConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ArrangementerConnectionEdges>>>;
};

export type Kategorier = Node & Document & {
  __typename?: 'Kategorier';
  value: Scalars['String']['output'];
  label: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type KategorierFilter = {
  value?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type KategorierConnectionEdges = {
  __typename?: 'KategorierConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Kategorier>;
};

export type KategorierConnection = Connection & {
  __typename?: 'KategorierConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<KategorierConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePages: Pages;
  createPages: Pages;
  updateUtdanning: Utdanning;
  createUtdanning: Utdanning;
  updateTjenester: Tjenester;
  createTjenester: Tjenester;
  updateBlogg: Blogg;
  createBlogg: Blogg;
  updateArrangementer: Arrangementer;
  createArrangementer: Arrangementer;
  updateKategorier: Kategorier;
  createKategorier: Kategorier;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdatePagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PagesMutation;
};


export type MutationCreatePagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PagesMutation;
};


export type MutationUpdateUtdanningArgs = {
  relativePath: Scalars['String']['input'];
  params: UtdanningMutation;
};


export type MutationCreateUtdanningArgs = {
  relativePath: Scalars['String']['input'];
  params: UtdanningMutation;
};


export type MutationUpdateTjenesterArgs = {
  relativePath: Scalars['String']['input'];
  params: TjenesterMutation;
};


export type MutationCreateTjenesterArgs = {
  relativePath: Scalars['String']['input'];
  params: TjenesterMutation;
};


export type MutationUpdateBloggArgs = {
  relativePath: Scalars['String']['input'];
  params: BloggMutation;
};


export type MutationCreateBloggArgs = {
  relativePath: Scalars['String']['input'];
  params: BloggMutation;
};


export type MutationUpdateArrangementerArgs = {
  relativePath: Scalars['String']['input'];
  params: ArrangementerMutation;
};


export type MutationCreateArrangementerArgs = {
  relativePath: Scalars['String']['input'];
  params: ArrangementerMutation;
};


export type MutationUpdateKategorierArgs = {
  relativePath: Scalars['String']['input'];
  params: KategorierMutation;
};


export type MutationCreateKategorierArgs = {
  relativePath: Scalars['String']['input'];
  params: KategorierMutation;
};

export type DocumentUpdateMutation = {
  pages?: InputMaybe<PagesMutation>;
  utdanning?: InputMaybe<UtdanningMutation>;
  tjenester?: InputMaybe<TjenesterMutation>;
  blogg?: InputMaybe<BloggMutation>;
  arrangementer?: InputMaybe<ArrangementerMutation>;
  kategorier?: InputMaybe<KategorierMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  pages?: InputMaybe<PagesMutation>;
  utdanning?: InputMaybe<UtdanningMutation>;
  tjenester?: InputMaybe<TjenesterMutation>;
  blogg?: InputMaybe<BloggMutation>;
  arrangementer?: InputMaybe<ArrangementerMutation>;
  kategorier?: InputMaybe<KategorierMutation>;
};

export type PagesHomepageTestimonialsMutation = {
  quote?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
};

export type PagesHomepageMutation = {
  heroImage?: InputMaybe<Scalars['String']['input']>;
  kicker?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  stat1Value?: InputMaybe<Scalars['String']['input']>;
  stat1Label?: InputMaybe<Scalars['String']['input']>;
  stat2Value?: InputMaybe<Scalars['String']['input']>;
  stat2Label?: InputMaybe<Scalars['String']['input']>;
  stat3Value?: InputMaybe<Scalars['String']['input']>;
  stat3Label?: InputMaybe<Scalars['String']['input']>;
  servicesHeading?: InputMaybe<Scalars['String']['input']>;
  aboutName?: InputMaybe<Scalars['String']['input']>;
  aboutText1?: InputMaybe<Scalars['String']['input']>;
  aboutText2?: InputMaybe<Scalars['String']['input']>;
  profileImage?: InputMaybe<Scalars['String']['input']>;
  testimonials?: InputMaybe<Array<InputMaybe<PagesHomepageTestimonialsMutation>>>;
  blogHeading?: InputMaybe<Scalars['String']['input']>;
  ctaTitle?: InputMaybe<Scalars['String']['input']>;
  ctaDescription?: InputMaybe<Scalars['String']['input']>;
};

export type PagesStandardVerdierMutation = {
  tittel?: InputMaybe<Scalars['String']['input']>;
  tekst?: InputMaybe<Scalars['String']['input']>;
};

export type PagesStandardMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  profileImage?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  verdier?: InputMaybe<Array<InputMaybe<PagesStandardVerdierMutation>>>;
};

export type PagesHeaderMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
};

export type PagesServicesFaqMutation = {
  question?: InputMaybe<Scalars['String']['input']>;
  answer?: InputMaybe<Scalars['String']['input']>;
};

export type PagesServicesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  infoBadge?: InputMaybe<Scalars['String']['input']>;
  faq?: InputMaybe<Array<InputMaybe<PagesServicesFaqMutation>>>;
};

export type PagesKontaktMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  kicker?: InputMaybe<Scalars['String']['input']>;
  heading?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  addressLine1?: InputMaybe<Scalars['String']['input']>;
  addressLine2?: InputMaybe<Scalars['String']['input']>;
  addressLine3?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  facebook?: InputMaybe<Scalars['String']['input']>;
  instagram?: InputMaybe<Scalars['String']['input']>;
  whatsapp?: InputMaybe<Scalars['String']['input']>;
};

export type PagesMutation = {
  homepage?: InputMaybe<PagesHomepageMutation>;
  standard?: InputMaybe<PagesStandardMutation>;
  header?: InputMaybe<PagesHeaderMutation>;
  services?: InputMaybe<PagesServicesMutation>;
  kontakt?: InputMaybe<PagesKontaktMutation>;
};

export type UtdanningMutation = {
  ar?: InputMaybe<Scalars['String']['input']>;
  grad?: InputMaybe<Scalars['String']['input']>;
  sted?: InputMaybe<Scalars['String']['input']>;
};

export type TjenesterPriserMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  pris?: InputMaybe<Scalars['String']['input']>;
};

export type TjenesterMutation = {
  malgruppe?: InputMaybe<Scalars['String']['input']>;
  orden?: InputMaybe<Scalars['Float']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  tittel?: InputMaybe<Scalars['String']['input']>;
  badge?: InputMaybe<Scalars['String']['input']>;
  undertittel?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['JSON']['input']>;
  detaljer?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  priser?: InputMaybe<Array<InputMaybe<TjenesterPriserMutation>>>;
};

export type BloggMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  readingTime?: InputMaybe<Scalars['Float']['input']>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ArrangementerMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['JSON']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  endDate?: InputMaybe<Scalars['String']['input']>;
  time?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['Float']['input']>;
  capacity?: InputMaybe<Scalars['Float']['input']>;
  kategorier?: InputMaybe<Scalars['String']['input']>;
  isOnline?: InputMaybe<Scalars['Boolean']['input']>;
};

export type KategorierMutation = {
  value?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type ImageFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type PagesHomepageTestimonialsFilter = {
  quote?: StringFilter | null | undefined;
  name?: StringFilter | null | undefined;
  role?: StringFilter | null | undefined;
};

export type PagesHomepageFilter = {
  heroImage?: ImageFilter | null | undefined;
  kicker?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  subtitle?: StringFilter | null | undefined;
  stat1Value?: StringFilter | null | undefined;
  stat1Label?: StringFilter | null | undefined;
  stat2Value?: StringFilter | null | undefined;
  stat2Label?: StringFilter | null | undefined;
  stat3Value?: StringFilter | null | undefined;
  stat3Label?: StringFilter | null | undefined;
  servicesHeading?: StringFilter | null | undefined;
  aboutName?: StringFilter | null | undefined;
  aboutText1?: StringFilter | null | undefined;
  aboutText2?: StringFilter | null | undefined;
  profileImage?: ImageFilter | null | undefined;
  testimonials?: PagesHomepageTestimonialsFilter | null | undefined;
  blogHeading?: StringFilter | null | undefined;
  ctaTitle?: StringFilter | null | undefined;
  ctaDescription?: StringFilter | null | undefined;
};

export type RichTextFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
};

export type PagesStandardVerdierFilter = {
  tittel?: StringFilter | null | undefined;
  tekst?: StringFilter | null | undefined;
};

export type PagesStandardFilter = {
  title?: StringFilter | null | undefined;
  subtitle?: StringFilter | null | undefined;
  intro?: StringFilter | null | undefined;
  profileImage?: ImageFilter | null | undefined;
  body?: RichTextFilter | null | undefined;
  verdier?: PagesStandardVerdierFilter | null | undefined;
};

export type PagesHeaderFilter = {
  title?: StringFilter | null | undefined;
  intro?: StringFilter | null | undefined;
};

export type PagesServicesFaqFilter = {
  question?: StringFilter | null | undefined;
  answer?: StringFilter | null | undefined;
};

export type PagesServicesFilter = {
  title?: StringFilter | null | undefined;
  subtitle?: StringFilter | null | undefined;
  intro?: StringFilter | null | undefined;
  infoBadge?: StringFilter | null | undefined;
  faq?: PagesServicesFaqFilter | null | undefined;
};

export type PagesKontaktFilter = {
  title?: StringFilter | null | undefined;
  kicker?: StringFilter | null | undefined;
  heading?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  addressLine1?: StringFilter | null | undefined;
  addressLine2?: StringFilter | null | undefined;
  addressLine3?: StringFilter | null | undefined;
  email?: StringFilter | null | undefined;
  phone?: StringFilter | null | undefined;
  facebook?: StringFilter | null | undefined;
  instagram?: StringFilter | null | undefined;
  whatsapp?: StringFilter | null | undefined;
};

export type PagesFilter = {
  homepage?: PagesHomepageFilter | null | undefined;
  standard?: PagesStandardFilter | null | undefined;
  header?: PagesHeaderFilter | null | undefined;
  services?: PagesServicesFilter | null | undefined;
  kontakt?: PagesKontaktFilter | null | undefined;
};

export type UtdanningFilter = {
  ar?: StringFilter | null | undefined;
  grad?: StringFilter | null | undefined;
  sted?: StringFilter | null | undefined;
};

export type NumberFilter = {
  lt?: number | null | undefined;
  lte?: number | null | undefined;
  gte?: number | null | undefined;
  gt?: number | null | undefined;
  eq?: number | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<number | null | undefined> | null | undefined;
};

export type TjenesterPriserFilter = {
  label?: StringFilter | null | undefined;
  pris?: StringFilter | null | undefined;
};

export type TjenesterFilter = {
  malgruppe?: StringFilter | null | undefined;
  orden?: NumberFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  tittel?: StringFilter | null | undefined;
  badge?: StringFilter | null | undefined;
  undertittel?: StringFilter | null | undefined;
  description?: RichTextFilter | null | undefined;
  detaljer?: StringFilter | null | undefined;
  priser?: TjenesterPriserFilter | null | undefined;
};

export type DatetimeFilter = {
  after?: string | null | undefined;
  before?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type BloggFilter = {
  title?: StringFilter | null | undefined;
  excerpt?: StringFilter | null | undefined;
  date?: DatetimeFilter | null | undefined;
  category?: StringFilter | null | undefined;
  readingTime?: NumberFilter | null | undefined;
  coverImage?: ImageFilter | null | undefined;
  body?: RichTextFilter | null | undefined;
};

export type ArrangementerKategorierFilter = {
  kategorier?: KategorierFilter | null | undefined;
};

export type BooleanFilter = {
  eq?: boolean | null | undefined;
  exists?: boolean | null | undefined;
};

export type ArrangementerFilter = {
  title?: StringFilter | null | undefined;
  description?: RichTextFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  date?: DatetimeFilter | null | undefined;
  endDate?: DatetimeFilter | null | undefined;
  time?: StringFilter | null | undefined;
  location?: StringFilter | null | undefined;
  price?: NumberFilter | null | undefined;
  capacity?: NumberFilter | null | undefined;
  kategorier?: ArrangementerKategorierFilter | null | undefined;
  isOnline?: BooleanFilter | null | undefined;
};

export type KategorierFilter = {
  value?: StringFilter | null | undefined;
  label?: StringFilter | null | undefined;
};

type PagesParts_PagesHomepage_Fragment = { __typename: 'PagesHomepage', heroImage: string | null, kicker: string | null, title: string, subtitle: string | null, stat1Value: string | null, stat1Label: string | null, stat2Value: string | null, stat2Label: string | null, stat3Value: string | null, stat3Label: string | null, servicesHeading: string | null, aboutName: string | null, aboutText1: string | null, aboutText2: string | null, profileImage: string | null, blogHeading: string | null, ctaTitle: string | null, ctaDescription: string | null, testimonials: Array<{ __typename: 'PagesHomepageTestimonials', quote: string, name: string, role: string | null } | null> | null };

type PagesParts_PagesStandard_Fragment = { __typename: 'PagesStandard', title: string, subtitle: string | null, intro: string | null, profileImage: string | null, body: any, verdier: Array<{ __typename: 'PagesStandardVerdier', tittel: string, tekst: string } | null> | null };

type PagesParts_PagesHeader_Fragment = { __typename: 'PagesHeader', title: string, intro: string | null };

type PagesParts_PagesServices_Fragment = { __typename: 'PagesServices', title: string, subtitle: string | null, intro: string | null, infoBadge: string | null, faq: Array<{ __typename: 'PagesServicesFaq', question: string, answer: string } | null> | null };

type PagesParts_PagesKontakt_Fragment = { __typename: 'PagesKontakt', title: string, kicker: string | null, heading: string, description: string, addressLine1: string | null, addressLine2: string | null, addressLine3: string | null, email: string, phone: string, facebook: string | null, instagram: string | null, whatsapp: string | null };

export type PagesPartsFragment =
  | PagesParts_PagesHomepage_Fragment
  | PagesParts_PagesStandard_Fragment
  | PagesParts_PagesHeader_Fragment
  | PagesParts_PagesServices_Fragment
  | PagesParts_PagesKontakt_Fragment
;

export type UtdanningPartsFragment = { __typename: 'Utdanning', ar: string, grad: string, sted: string };

export type TjenesterPartsFragment = { __typename: 'Tjenester', malgruppe: string, orden: number | null, image: string | null, tittel: string, badge: string | null, undertittel: string, description: any, detaljer: Array<string | null> | null, priser: Array<{ __typename: 'TjenesterPriser', label: string, pris: string } | null> | null };

export type BloggPartsFragment = { __typename: 'Blogg', title: string, excerpt: string, date: string, category: string | null, readingTime: number | null, coverImage: string | null, body: any };

export type ArrangementerPartsFragment = { __typename: 'Arrangementer', title: string, description: any, image: string | null, date: string, endDate: string | null, time: string, location: string, price: number, capacity: number | null, isOnline: boolean | null, kategorier: { __typename: 'Kategorier', value: string, label: string, id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type KategorierPartsFragment = { __typename: 'Kategorier', value: string, label: string };

export type PagesQueryVariables = Exact<{
  relativePath: string;
}>;


export type PagesQuery = { pages:
    | { __typename: 'PagesHomepage', id: string, heroImage: string | null, kicker: string | null, title: string, subtitle: string | null, stat1Value: string | null, stat1Label: string | null, stat2Value: string | null, stat2Label: string | null, stat3Value: string | null, stat3Label: string | null, servicesHeading: string | null, aboutName: string | null, aboutText1: string | null, aboutText2: string | null, profileImage: string | null, blogHeading: string | null, ctaTitle: string | null, ctaDescription: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, testimonials: Array<{ __typename: 'PagesHomepageTestimonials', quote: string, name: string, role: string | null } | null> | null }
    | { __typename: 'PagesStandard', id: string, title: string, subtitle: string | null, intro: string | null, profileImage: string | null, body: any, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, verdier: Array<{ __typename: 'PagesStandardVerdier', tittel: string, tekst: string } | null> | null }
    | { __typename: 'PagesHeader', id: string, title: string, intro: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } }
    | { __typename: 'PagesServices', id: string, title: string, subtitle: string | null, intro: string | null, infoBadge: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, faq: Array<{ __typename: 'PagesServicesFaq', question: string, answer: string } | null> | null }
    | { __typename: 'PagesKontakt', id: string, title: string, kicker: string | null, heading: string, description: string, addressLine1: string | null, addressLine2: string | null, addressLine3: string | null, email: string, phone: string, facebook: string | null, instagram: string | null, whatsapp: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } }
   };

export type PagesConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: PagesFilter | null | undefined;
}>;


export type PagesConnectionQuery = { pagesConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node:
        | { __typename: 'PagesHomepage', id: string, heroImage: string | null, kicker: string | null, title: string, subtitle: string | null, stat1Value: string | null, stat1Label: string | null, stat2Value: string | null, stat2Label: string | null, stat3Value: string | null, stat3Label: string | null, servicesHeading: string | null, aboutName: string | null, aboutText1: string | null, aboutText2: string | null, profileImage: string | null, blogHeading: string | null, ctaTitle: string | null, ctaDescription: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, testimonials: Array<{ __typename: 'PagesHomepageTestimonials', quote: string, name: string, role: string | null } | null> | null }
        | { __typename: 'PagesStandard', id: string, title: string, subtitle: string | null, intro: string | null, profileImage: string | null, body: any, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, verdier: Array<{ __typename: 'PagesStandardVerdier', tittel: string, tekst: string } | null> | null }
        | { __typename: 'PagesHeader', id: string, title: string, intro: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } }
        | { __typename: 'PagesServices', id: string, title: string, subtitle: string | null, intro: string | null, infoBadge: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, faq: Array<{ __typename: 'PagesServicesFaq', question: string, answer: string } | null> | null }
        | { __typename: 'PagesKontakt', id: string, title: string, kicker: string | null, heading: string, description: string, addressLine1: string | null, addressLine2: string | null, addressLine3: string | null, email: string, phone: string, facebook: string | null, instagram: string | null, whatsapp: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } }
       | null } | null> | null } };

export type UtdanningQueryVariables = Exact<{
  relativePath: string;
}>;


export type UtdanningQuery = { utdanning: { __typename: 'Utdanning', id: string, ar: string, grad: string, sted: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type UtdanningConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: UtdanningFilter | null | undefined;
}>;


export type UtdanningConnectionQuery = { utdanningConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Utdanning', id: string, ar: string, grad: string, sted: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type TjenesterQueryVariables = Exact<{
  relativePath: string;
}>;


export type TjenesterQuery = { tjenester: { __typename: 'Tjenester', id: string, malgruppe: string, orden: number | null, image: string | null, tittel: string, badge: string | null, undertittel: string, description: any, detaljer: Array<string | null> | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, priser: Array<{ __typename: 'TjenesterPriser', label: string, pris: string } | null> | null } };

export type TjenesterConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: TjenesterFilter | null | undefined;
}>;


export type TjenesterConnectionQuery = { tjenesterConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Tjenester', id: string, malgruppe: string, orden: number | null, image: string | null, tittel: string, badge: string | null, undertittel: string, description: any, detaljer: Array<string | null> | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, priser: Array<{ __typename: 'TjenesterPriser', label: string, pris: string } | null> | null } | null } | null> | null } };

export type BloggQueryVariables = Exact<{
  relativePath: string;
}>;


export type BloggQuery = { blogg: { __typename: 'Blogg', id: string, title: string, excerpt: string, date: string, category: string | null, readingTime: number | null, coverImage: string | null, body: any, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type BloggConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: BloggFilter | null | undefined;
}>;


export type BloggConnectionQuery = { bloggConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Blogg', id: string, title: string, excerpt: string, date: string, category: string | null, readingTime: number | null, coverImage: string | null, body: any, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ArrangementerQueryVariables = Exact<{
  relativePath: string;
}>;


export type ArrangementerQuery = { arrangementer: { __typename: 'Arrangementer', id: string, title: string, description: any, image: string | null, date: string, endDate: string | null, time: string, location: string, price: number, capacity: number | null, isOnline: boolean | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, kategorier: { __typename: 'Kategorier', value: string, label: string, id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } } };

export type ArrangementerConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: ArrangementerFilter | null | undefined;
}>;


export type ArrangementerConnectionQuery = { arrangementerConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Arrangementer', id: string, title: string, description: any, image: string | null, date: string, endDate: string | null, time: string, location: string, price: number, capacity: number | null, isOnline: boolean | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, kategorier: { __typename: 'Kategorier', value: string, label: string, id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } } | null } | null> | null } };

export type KategorierQueryVariables = Exact<{
  relativePath: string;
}>;


export type KategorierQuery = { kategorier: { __typename: 'Kategorier', id: string, value: string, label: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type KategorierConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: KategorierFilter | null | undefined;
}>;


export type KategorierConnectionQuery = { kategorierConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Kategorier', id: string, value: string, label: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const PagesPartsFragmentDoc = gql`
    fragment PagesParts on Pages {
  __typename
  ... on PagesHomepage {
    heroImage
    kicker
    title
    subtitle
    stat1Value
    stat1Label
    stat2Value
    stat2Label
    stat3Value
    stat3Label
    servicesHeading
    aboutName
    aboutText1
    aboutText2
    profileImage
    testimonials {
      __typename
      quote
      name
      role
    }
    blogHeading
    ctaTitle
    ctaDescription
  }
  ... on PagesStandard {
    title
    subtitle
    intro
    profileImage
    body
    verdier {
      __typename
      tittel
      tekst
    }
  }
  ... on PagesHeader {
    title
    intro
  }
  ... on PagesServices {
    title
    subtitle
    intro
    infoBadge
    faq {
      __typename
      question
      answer
    }
  }
  ... on PagesKontakt {
    title
    kicker
    heading
    description
    addressLine1
    addressLine2
    addressLine3
    email
    phone
    facebook
    instagram
    whatsapp
  }
}
    `;
export const UtdanningPartsFragmentDoc = gql`
    fragment UtdanningParts on Utdanning {
  __typename
  ar
  grad
  sted
}
    `;
export const TjenesterPartsFragmentDoc = gql`
    fragment TjenesterParts on Tjenester {
  __typename
  malgruppe
  orden
  image
  tittel
  badge
  undertittel
  description
  detaljer
  priser {
    __typename
    label
    pris
  }
}
    `;
export const BloggPartsFragmentDoc = gql`
    fragment BloggParts on Blogg {
  __typename
  title
  excerpt
  date
  category
  readingTime
  coverImage
  body
}
    `;
export const ArrangementerPartsFragmentDoc = gql`
    fragment ArrangementerParts on Arrangementer {
  __typename
  title
  description
  image
  date
  endDate
  time
  location
  price
  capacity
  kategorier {
    ... on Kategorier {
      __typename
      value
      label
    }
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
  }
  isOnline
}
    `;
export const KategorierPartsFragmentDoc = gql`
    fragment KategorierParts on Kategorier {
  __typename
  value
  label
}
    `;
export const PagesDocument = gql`
    query pages($relativePath: String!) {
  pages(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PagesParts
  }
}
    ${PagesPartsFragmentDoc}`;
export const PagesConnectionDocument = gql`
    query pagesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PagesFilter) {
  pagesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PagesParts
      }
    }
  }
}
    ${PagesPartsFragmentDoc}`;
export const UtdanningDocument = gql`
    query utdanning($relativePath: String!) {
  utdanning(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...UtdanningParts
  }
}
    ${UtdanningPartsFragmentDoc}`;
export const UtdanningConnectionDocument = gql`
    query utdanningConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: UtdanningFilter) {
  utdanningConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...UtdanningParts
      }
    }
  }
}
    ${UtdanningPartsFragmentDoc}`;
export const TjenesterDocument = gql`
    query tjenester($relativePath: String!) {
  tjenester(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TjenesterParts
  }
}
    ${TjenesterPartsFragmentDoc}`;
export const TjenesterConnectionDocument = gql`
    query tjenesterConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TjenesterFilter) {
  tjenesterConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TjenesterParts
      }
    }
  }
}
    ${TjenesterPartsFragmentDoc}`;
export const BloggDocument = gql`
    query blogg($relativePath: String!) {
  blogg(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BloggParts
  }
}
    ${BloggPartsFragmentDoc}`;
export const BloggConnectionDocument = gql`
    query bloggConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BloggFilter) {
  bloggConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BloggParts
      }
    }
  }
}
    ${BloggPartsFragmentDoc}`;
export const ArrangementerDocument = gql`
    query arrangementer($relativePath: String!) {
  arrangementer(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ArrangementerParts
  }
}
    ${ArrangementerPartsFragmentDoc}`;
export const ArrangementerConnectionDocument = gql`
    query arrangementerConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ArrangementerFilter) {
  arrangementerConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ArrangementerParts
      }
    }
  }
}
    ${ArrangementerPartsFragmentDoc}`;
export const KategorierDocument = gql`
    query kategorier($relativePath: String!) {
  kategorier(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...KategorierParts
  }
}
    ${KategorierPartsFragmentDoc}`;
export const KategorierConnectionDocument = gql`
    query kategorierConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: KategorierFilter) {
  kategorierConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...KategorierParts
      }
    }
  }
}
    ${KategorierPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      pages(variables: PagesQueryVariables, options?: C): Promise<{data: PagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesQueryVariables, query: string}> {
        return requester<{data: PagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesQueryVariables, query: string}, PagesQueryVariables>(PagesDocument, variables, options);
      },
    pagesConnection(variables?: PagesConnectionQueryVariables, options?: C): Promise<{data: PagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesConnectionQueryVariables, query: string}> {
        return requester<{data: PagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesConnectionQueryVariables, query: string}, PagesConnectionQueryVariables>(PagesConnectionDocument, variables, options);
      },
    utdanning(variables: UtdanningQueryVariables, options?: C): Promise<{data: UtdanningQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: UtdanningQueryVariables, query: string}> {
        return requester<{data: UtdanningQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: UtdanningQueryVariables, query: string}, UtdanningQueryVariables>(UtdanningDocument, variables, options);
      },
    utdanningConnection(variables?: UtdanningConnectionQueryVariables, options?: C): Promise<{data: UtdanningConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: UtdanningConnectionQueryVariables, query: string}> {
        return requester<{data: UtdanningConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: UtdanningConnectionQueryVariables, query: string}, UtdanningConnectionQueryVariables>(UtdanningConnectionDocument, variables, options);
      },
    tjenester(variables: TjenesterQueryVariables, options?: C): Promise<{data: TjenesterQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TjenesterQueryVariables, query: string}> {
        return requester<{data: TjenesterQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TjenesterQueryVariables, query: string}, TjenesterQueryVariables>(TjenesterDocument, variables, options);
      },
    tjenesterConnection(variables?: TjenesterConnectionQueryVariables, options?: C): Promise<{data: TjenesterConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TjenesterConnectionQueryVariables, query: string}> {
        return requester<{data: TjenesterConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TjenesterConnectionQueryVariables, query: string}, TjenesterConnectionQueryVariables>(TjenesterConnectionDocument, variables, options);
      },
    blogg(variables: BloggQueryVariables, options?: C): Promise<{data: BloggQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BloggQueryVariables, query: string}> {
        return requester<{data: BloggQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BloggQueryVariables, query: string}, BloggQueryVariables>(BloggDocument, variables, options);
      },
    bloggConnection(variables?: BloggConnectionQueryVariables, options?: C): Promise<{data: BloggConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BloggConnectionQueryVariables, query: string}> {
        return requester<{data: BloggConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BloggConnectionQueryVariables, query: string}, BloggConnectionQueryVariables>(BloggConnectionDocument, variables, options);
      },
    arrangementer(variables: ArrangementerQueryVariables, options?: C): Promise<{data: ArrangementerQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArrangementerQueryVariables, query: string}> {
        return requester<{data: ArrangementerQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArrangementerQueryVariables, query: string}, ArrangementerQueryVariables>(ArrangementerDocument, variables, options);
      },
    arrangementerConnection(variables?: ArrangementerConnectionQueryVariables, options?: C): Promise<{data: ArrangementerConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArrangementerConnectionQueryVariables, query: string}> {
        return requester<{data: ArrangementerConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArrangementerConnectionQueryVariables, query: string}, ArrangementerConnectionQueryVariables>(ArrangementerConnectionDocument, variables, options);
      },
    kategorier(variables: KategorierQueryVariables, options?: C): Promise<{data: KategorierQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: KategorierQueryVariables, query: string}> {
        return requester<{data: KategorierQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: KategorierQueryVariables, query: string}, KategorierQueryVariables>(KategorierDocument, variables, options);
      },
    kategorierConnection(variables?: KategorierConnectionQueryVariables, options?: C): Promise<{data: KategorierConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: KategorierConnectionQueryVariables, query: string}> {
        return requester<{data: KategorierConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: KategorierConnectionQueryVariables, query: string}, KategorierConnectionQueryVariables>(KategorierConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  