/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TjenesterIndexRouteImport } from './routes/tjenester/index'
import { Route as OmMegIndexRouteImport } from './routes/om-meg/index'
import { Route as BloggIndexRouteImport } from './routes/blogg/index'
import { Route as ArrangementerIndexRouteImport } from './routes/arrangementer/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as BloggSlugRouteImport } from './routes/blogg/$slug'
import { Route as AdminSplatRouteImport } from './routes/admin/$'

const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TjenesterIndexRoute = TjenesterIndexRouteImport.update({
  id: '/tjenester/',
  path: '/tjenester/',
  getParentRoute: () => rootRouteImport,
} as any)
const OmMegIndexRoute = OmMegIndexRouteImport.update({
  id: '/om-meg/',
  path: '/om-meg/',
  getParentRoute: () => rootRouteImport,
} as any)
const BloggIndexRoute = BloggIndexRouteImport.update({
  id: '/blogg/',
  path: '/blogg/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrangementerIndexRoute = ArrangementerIndexRouteImport.update({
  id: '/arrangementer/',
  path: '/arrangementer/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const BloggSlugRoute = BloggSlugRouteImport.update({
  id: '/blogg/$slug',
  path: '/blogg/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/admin/$': typeof AdminSplatRoute
  '/blogg/$slug': typeof BloggSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/arrangementer/': typeof ArrangementerIndexRoute
  '/blogg/': typeof BloggIndexRoute
  '/om-meg/': typeof OmMegIndexRoute
  '/tjenester/': typeof TjenesterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/admin/$': typeof AdminSplatRoute
  '/blogg/$slug': typeof BloggSlugRoute
  '/admin': typeof AdminIndexRoute
  '/arrangementer': typeof ArrangementerIndexRoute
  '/blogg': typeof BloggIndexRoute
  '/om-meg': typeof OmMegIndexRoute
  '/tjenester': typeof TjenesterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/admin/$': typeof AdminSplatRoute
  '/blogg/$slug': typeof BloggSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/arrangementer/': typeof ArrangementerIndexRoute
  '/blogg/': typeof BloggIndexRoute
  '/om-meg/': typeof OmMegIndexRoute
  '/tjenester/': typeof TjenesterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kontakt'
    | '/admin/$'
    | '/blogg/$slug'
    | '/admin/'
    | '/arrangementer/'
    | '/blogg/'
    | '/om-meg/'
    | '/tjenester/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kontakt'
    | '/admin/$'
    | '/blogg/$slug'
    | '/admin'
    | '/arrangementer'
    | '/blogg'
    | '/om-meg'
    | '/tjenester'
  id:
    | '__root__'
    | '/'
    | '/kontakt'
    | '/admin/$'
    | '/blogg/$slug'
    | '/admin/'
    | '/arrangementer/'
    | '/blogg/'
    | '/om-meg/'
    | '/tjenester/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktRoute: typeof KontaktRoute
  AdminSplatRoute: typeof AdminSplatRoute
  BloggSlugRoute: typeof BloggSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ArrangementerIndexRoute: typeof ArrangementerIndexRoute
  BloggIndexRoute: typeof BloggIndexRoute
  OmMegIndexRoute: typeof OmMegIndexRoute
  TjenesterIndexRoute: typeof TjenesterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tjenester/': {
      id: '/tjenester/'
      path: '/tjenester'
      fullPath: '/tjenester/'
      preLoaderRoute: typeof TjenesterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-meg/': {
      id: '/om-meg/'
      path: '/om-meg'
      fullPath: '/om-meg/'
      preLoaderRoute: typeof OmMegIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogg/': {
      id: '/blogg/'
      path: '/blogg'
      fullPath: '/blogg/'
      preLoaderRoute: typeof BloggIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrangementer/': {
      id: '/arrangementer/'
      path: '/arrangementer'
      fullPath: '/arrangementer/'
      preLoaderRoute: typeof ArrangementerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogg/$slug': {
      id: '/blogg/$slug'
      path: '/blogg/$slug'
      fullPath: '/blogg/$slug'
      preLoaderRoute: typeof BloggSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktRoute: KontaktRoute,
  AdminSplatRoute: AdminSplatRoute,
  BloggSlugRoute: BloggSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  ArrangementerIndexRoute: ArrangementerIndexRoute,
  BloggIndexRoute: BloggIndexRoute,
  OmMegIndexRoute: OmMegIndexRoute,
  TjenesterIndexRoute: TjenesterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
